name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Docker Buildx (optional, untuk build Docker di GitHub Actions)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Buat file .env dengan variabel lingkungan
      - name: Create .env file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env

      # Build Docker image dan kirim environment variables
      - name: Build Docker image
        run: |
          docker build -t nest-app . 
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

      # Run Docker container dengan environment variables
      - name: Run Docker container
        run: |
          docker run -d -p 3000:3000 \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
            nest-app
